class Account {
    /**
     * @param {Object} data
     * @param {AccountTypes} type
     */
    constructor(data, type) {
        /**
         * Unique ID for this account that is generated by the static Account.generateUniqueId() method.
         * @type {string}
         * @example
         * ropsten:0xab21ef13...ac23fe
         */
        this.id = data.id;

        /** @type string */
        this.address = data.address;

        /** @type NetworkTypes */
        this.network = data.network;

        /** @type {AccountTypes} */
        this.type = type;
    }

    /**
     * @param {string} address
     * @param {NetworkTypes} network
     * @return {string}
     */
    static generateUniqueId(address, network) {
        return `${network}:${address}`;
    }
}

export default Account;
