name: Continous Integration - Production

on:
  push:
    branches:
      - master
    paths:
      - 'package.json'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Install dependencies
        uses: Borales/actions-yarn@master
        with:
          args: install
      - name: Run yarn test
        uses: Borales/actions-yarn@master
        with:
          args: test:ci
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Tag with version from package.json
        uses: butlerlogic/action-autotag@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefx: "v"

